services:
  - type: web
    name: xanhsm-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: OPENAI_API_KEY
        sync: false

  - type: web
    name: xanhsm
    runtime: docker
    dockerfilePath: ./frontend/Dockerfile
    dockerContext: ./frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        value: https://xanhsm-api.onrender.com
